#!/bin/bash

echo "<!DOCTYPE html>"
echo "<html>"

if [ -z "$user" ]
then
    echo "<h2>Grades</h2>"
    echo "<form action=\"grades\" method=\"GET\">"
    echo "Enter your cs account:<br>"
    echo "<input type=\"text\" name=\"user\"><br>"
    echo "<input type=\"submit\" value=\"Enter\">"
    echo "</form>"
else
    echo $(./website/calcgrade.sh $user)
fi

echo "</html>"
