#!/bin/bash

echo "<!DOCTYPE html>"
echo "<html>"

echo "<head>"
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"stylesheet.css\" >"
echo "<title>Grades</title>"
echo "</head>"

echo "<body>"

if [ -z "$user" ]
then
    echo "<h2>Grades</h2>"
    echo "<form action=\"grades\" method=\"GET\" class=\"gradeform\">"
    echo "Enter your cs account:<br>"
    echo "<input type=\"text\" name=\"user\"><br>"
    echo "<input type=\"submit\" value=\"Enter\" class=\"button\">"
    echo "</form>"
else
    echo $(./website/calcgrade.sh $user)
fi

echo "<br><br>"
echo "<a href=\"..\">Home</a>"

echo "</body>"

echo "</html>"
